### ISSUE TITLE
你好，默认值怎么设置啊

### ISSUE THREAD

**Issue by d1025ok** [Charming2015/el-cascader-multi#10]

**Comment by Charming2015** [comment]
v-model就可以绑定默认值呀

**Comment by fox19920726** [comment]
v-model里设置默认值的格式是什么呀？

**Comment by Charming2015** [comment]
> v-model里设置默认值的格式是什么呀？

可以看一下这个在线demo：https://charming2015.github.io/el-cascader-multi-demo/dist/index.html

**Comment by fox19920726** [comment]
> > v-model里设置默认值的格式是什么呀？
> 
> 可以看一下这个在线demo：https://charming2015.github.io/el-cascader-multi-demo/dist/index.html

嗯，为防止别的小伙伴搞不清楚，我在这里写一下设置默认值的方法：
可以给v-module设置默认值，且v-module的格式为：[['zhinan','shejiyuanze','yizhi']]
