### ISSUE TITLE
开启 filterable和collapse-tags 问题

### ISSUE THREAD

**Issue by jaihao** [Charming2015/el-cascader-multi#14]
1、开启 filterable和collapse-tags 为true  时，搜索后按回车可以选中搜索出来的内容，但是checkList中并没有
2、按backspace 键减掉数量问题，checkList中的值也没有改变

**Comment by Charming2015** [comment]
你好，在1.1.6版本修复了！
测试还有问题欢迎继续联系我哦，喜欢的话麻烦给个星星哈

**Comment by alwsu** [comment]
在用tag上的差删除时，有部分tag删除不掉，通过remove-tag打印的checked: false但还是没删除。
通过复选框可以取消。
