### ISSUE TITLE
不能选中

### ISSUE THREAD

**Issue by 1170337548** [Charming2015/el-cascader-multi#2]
你好，不能选中是怎么回事呀
![image](https://user-images.githubusercontent.com/24436179/54011943-4d17d300-41af-11e9-9828-c2f47b2ccba1.png)

**Comment by Charming2015** [comment]
你好，请问可以重现问题吗？

**Comment by 1170337548** [comment]
谢谢你，这个问题已用其他方法处理。当初这里是出现点击了选项前面的checkbox不是选中状态

**Comment by f0307yy** [comment]
我也是无法选中，请问是怎么解决的？

**Comment by DemoHu** [comment]
同样不能选中，请问是怎么回事

**Comment by grace618** [comment]
也是选中不划勾

**Comment by DemoHu** [comment]
> 谢谢你，这个问题已用其他方法处理。当初这里是出现点击了选项前面的checkbox不是选中状态

你好，请问你是怎么解决的？

**Comment by Charming2015** [comment]
修复了，谢谢大家提出问题
