### ISSUE TITLE
突然不能使用了

### ISSUE THREAD

**Issue by luuuuuufei** [Charming2015/el-cascader-multi#20]
"TypeError: Cannot read property 'length' of null"
found in
---> <ElCascaderMulti> at node_modules\el-cascader-multi\src\multi-cascader\multi-cascader.vue
页面报错

**Comment by luuuuuufei** [comment]
传入的data数据也是array，一开始还好用，后来突然就不行了，页面报错

**Comment by luuuuuufei** [comment]
有大神能给解答一下吗，data传入的也是array格式的数据，就是不行，显示不出来。

**Comment by luuuuuufei** [comment]
array 数据字段为value，label，children，

**Comment by Charming2015** [comment]
方便截图报错，复制代码，让我复现问题吗？

**Comment by luuuuuufei** [comment]
不好意思啊，不能复制代码，可以说一下，问题已经解决了，用的比较笨的方法，就是后台数据是拼接的这种父子数组，前台得到后，直接拆分重组。。。可以展示了。。
