### ISSUE TITLE
Duplicate keys detected: 'xxx'. This may cause an update error.

### ISSUE THREAD

**Issue by piemonSong** [Charming2015/el-cascader-multi#3]
render-list.vue 中的循环，如果数据量大一些的话，可能会出现重复key。
下面是我用600个数据进行测试
![image](https://user-images.githubusercontent.com/11419396/54348996-498bbc80-4685-11e9-9aba-5705e42d5203.png)

**Comment by Charming2015** [comment]
对，这个问题我考虑过，我一开始打算用层级-层级-值（a-b-c）这种形式来实现值的绑定，但是发现这种绑定形式对于小量重复性低的用户来说，一开始的绑定会比较恶心。

谢谢建议，近期我会考虑优化这个东西

**Comment by Charming2015** [comment]
修复了，谢谢支持
