### ISSUE TITLE
选择后，只有最有一级的value，没有前几级的值

### ISSUE THREAD

**Issue by xinbingyao** [Charming2015/el-cascader-multi#7]
例如： 北京 朝阳区 [ 10, 1001]

**Comment by Charming2015** [comment]
有道理，我现在改一下

**Comment by xinbingyao** [comment]
太好了




------------------ 原始邮件 ------------------
发件人: "Charming2015"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 上午10:34
收件人: "Charming2015/el-cascader-multi"<el-cascader-multi@noreply.github.com>; 
抄送: "辛柄瑶"<xinbingyao55@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Charming2015/el-cascader-multi] 选择后，只有最有一级的value，没有前几级的值 (#7)




有道理，我现在改一下

**Comment by Charming2015** [comment]
> 太好了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Charming2015"<notifications@github.com>; 发送时间: 2019年4月23日(星期二) 上午10:34 收件人: "Charming2015/el-cascader-multi"<el-cascader-multi@noreply.github.com>; 抄送: "辛柄瑶"<xinbingyao55@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [Charming2015/el-cascader-multi] 选择后，只有最有一级的value，没有前几级的值 (#7) 有道理，我现在改一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

支持了！喜欢的话麻烦给颗星星~

**Comment by xinbingyao** [comment]
必须的！



------------------ 原始邮件 ------------------
发件人: "Charming2015"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 中午12:39
收件人: "Charming2015/el-cascader-multi"<el-cascader-multi@noreply.github.com>; 
抄送: "辛柄瑶"<xinbingyao55@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Charming2015/el-cascader-multi] 选择后，只有最有一级的value，没有前几级的值 (#7)



 
太好了
 …
 ------------------ 原始邮件 ------------------ 发件人: "Charming2015"notifications@github.com; 发送时间: 2019年4月23日(星期二) 上午10:34 收件人: "Charming2015/el-cascader-multi"el-cascader-multi@noreply.github.com; 抄送: "辛柄瑶"xinbingyao55@qq.com; "Author"author@noreply.github.com; 主题: Re: [Charming2015/el-cascader-multi] 选择后，只有最有一级的value，没有前几级的值 (#7) 有道理，我现在改一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
支持了！喜欢的话麻烦给颗星星~
