### ISSUE TITLE
你这个v-model数据好像没有双向绑定

### ISSUE THREAD

**Issue by 17610172271** [Charming2015/el-cascader-multi#8]

**Comment by Charming2015** [comment]
emmm我刚才测试了下好像没问题。
如果你还是出现这个bug，可以跟我说说你的详细的开发环境，以及稳定重现这个bug的方法吗？

**Comment by 17610172271** [comment]
编辑的时候第一次点击  获取数据渲染上去没问题  点第二条数据的编辑  赋值给这个组件勾中的还是第一次编辑的   我每次编辑的弹窗用v-if的话才能正常

**Comment by Charming2015** [comment]
我大概懂你的意思了。
其实不是**v-model数据好像没有双向绑定**
而是，**通过代码更改value时，没有更新选中状态**

现在已经支持啦~欢迎有问题继续提出哦。喜欢的话麻烦点个star哈
